### ISSUE TITLE
DemoScript_Password processing is failing 

### ISSUE THREAD

**Issue by aparnakamat** [NutriSafe-DLT/nutrisafe#34]
Python version **2.7.16**

**Steps to Reproduce:**
1.Start the cmd and navigate to **demodata** folder
2.Type command '**python3 generate_demodata.py**' and **Enter**
3.Enter the selection e.g **enter '1'**
4.Enter **admin password** and hit **Enter**
5.Observe

**Actual Result:**
An error message is generated.

**Expected Result:**
The script should be successfully executed.

**ScreenShot:**
 
![image](https://user-images.githubusercontent.com/79140280/122742642-74164800-d286-11eb-9894-81a51632c106.png)
![image](https://user-images.githubusercontent.com/79140280/122742696-82fcfa80-d286-11eb-908f-c722d6bccf86.png)
![image](https://user-images.githubusercontent.com/79140280/122742799-9dcf6f00-d286-11eb-8fb6-949cda1e57db.png)

**Comment by CodingSinceThe80s** [comment]
Just a note that I can reproduce the issue with python3, works fine with python (2.7). Nevertheless both should be supported so will fix

**Comment by CodingSinceThe80s** [comment]
Fixed in #35
